name: recipez
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  generic_bloc_provider: ^2.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  path: ^1.8.1
  auto_size_text: ^3.0.0
  art_sweetalert: ^0.0.5
  card_loading: ^0.3.2
  marquee: ^2.2.3
  device_preview: ^1.1.0
  fading_edge_scrollview: ^4.1.1
  sticky_headers: ^0.3.0
  purchases_flutter: ^8.7.2
  animated_text_kit: ^4.2.2
  webview_flutter: ^4.7.0
  
  # Clean Architecture
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  http_auth: ^1.0.4
  http: ^1.3.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
